global_frame: map
robot_base_frame: base_footprint
transform_tolerance: 0.2
robot_radius: 0.6

update_frequency: 5.0
publish_frequency: 2.0
rolling_window: false

width: 100
height: 100
resolution: 0.05
origin_x: -50
origin_y: -50

plugins:
  - {name: static, type: "costmap_2d::StaticLayer"}
#  - {name: inflation, type: "costmap_2d::InflationLayer"}

static:
  unknown_cost_value: -1
  lethal_cost_threshold: 100
  map_topic: map

# inflation:
#   inflation_radius: 1.1
#   cost_scaling_factor: 0.2